02-week/lotr/config/routes.rb
Rails.application.routes.draw do
  get 'game/mordor'

  get 'game/gate'

  get 'game/stairs'

  get 'game/trolls'

  get 'game/tunnel'

  get 'game/ring'

  get 'game/sting'

  get 'game/rock'

  get 'game/life'

  get 'game/death'

end

02-week/lotr/app/controllers/game_controller.rb
class GameController < ApplicationController
  def mordor
  end

  def gate
  end

  def stairs
  end

  def trolls
  end

  def tunnel
  end

  def ring
  end

  def sting
  end

  def rock
  end

  def life
  end

  def death
  end
end

02-week/lotr/app/helpers/game_helper.rb
module GameHelper
end

02-week/lotr/app/views/game/death.html.erb
<h1>Bad Choice!</h1>
<p>You have decided the fate of your life and the lives of all good creatures in Middle Earth.
  Sauron has detected your location and will come to destroy you! Your friends will die. Sorry!</p>

02-week/lotr/app/views/game/gate.html.erb
<h1>You chose the Black Gate!</h1>
<p>Five minutes after entering through the front door to Mordor, you are confronted by a group of 3 trolls.</p>
<p>Choose your weapon...</p>
<p><%= link_to "The Ring of Power", game_ring_path %></p>
<p><%= link_to "Sting", game_sting_path %></p>

02-week/lotr/app/views/game/life.html.erb
<h1>You Escaped!</h1>
<p>Your courage and bravery has paid-off! Because you resisted the Ring, your mission is safe and secret! Good job!</p>

02-week/lotr/app/views/game/mordor.html.erb
<h1>Welcome to the Lord of the Rings Official Game!</h1>
<p>You are Frodo. Your mission is to destroy the ring of power. You have managed to work your way to the Black Gate of Mordor. However, the gate is heavily guarded.</p>
<p>You must decide whether to attempt to enter through the Black Gate or take the stairs that your guide, Gollum, suggests.</p>
<p>Take the <%= link_to "Black Gate", game_gate_path %></p>
<p>Take the <%= link_to "stairs", game_stairs_path %></p>

02-week/lotr/app/views/game/ring.html.erb
<h1>You are now visible to the trolls!</h1>
<p>Because they serve the dark lord, Sauron, they have the ability to see you even with the ring on your finger! You have been eliminated from Middle Earth. Better luck next time!</p>

02-week/lotr/app/views/game/rock.html.erb
<h1>Game#rock</h1>
<p>Find me in app/views/game/rock.html.erb</p>

02-week/lotr/app/views/game/stairs.html.erb
<h1>You chose to take the stairs that Gollum recommended.</h1>
<p>Gollum has led you up the stairs and to a dark tunnel. You enter the cave and discover that
  Gollum has abandoned you. Without a guide, you are hopelessly lost. Suddenly, a giant spider leaps out
  of the shadows and attempts to attack you!!!!! You must fight back!</p>
<p><%= link_to "Put on the Ring", game_death_path %></p>
<p><%= link_to "Fight with a rock", game_life_path %></p>

02-week/lotr/app/views/game/sting.html.erb
<h1>The Trolls have been frightened off!</h1>
<p>Your path is now secure. Continue through Mordor. Remain cautious however! Danger lies around every corner.</p>

02-week/lotr/app/views/game/trolls.html.erb
<h1>Game#trolls</h1>
<p>Find me in app/views/game/trolls.html.erb</p>

02-week/lotr/app/views/game/tunnel.html.erb
<h1>Game#tunnel</h1>
<p>Find me in app/views/game/tunnel.html.erb</p>

02-week/lotr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lotr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>